### ISSUE TITLE
2D functions?

### ISSUE THREAD

**Issue by nschiett** [jmadinlab/habtools#16]
Circularity: in 2D perimeter divided by perimeter of circle with same area

**Comment by nschiett** [comment]
Do we want 2D functions? eg linear rugosity, box counting fd

**Comment by jmadin** [comment]
Tempted to not put in.  Focus on 3D and reconsider later?  Or user requests?

**Comment by jmadin** [comment]
I've added `perimeter()`, `circularity()` and `fd_boxes()`. We can use geometry package to get area. I think we can close this and await further requests. 👍
