### ISSUE TITLE
can cell_count give a number that is higher than n? 

### ISSUE THREAD

**Issue by nschiett** [jmadinlab/habtools#34]
Here's a reproducible example. Is this normal behavior of the function? 
I stumbled upon this by trying to add an example for these functions
``` 
pts <- data.frame(x = rnorm(100, 0, 5))
cell_count_1d(pts, xmin = min(pts$x), xmax = max(pts$x), n = 5)
# gives 6
```

**Comment by jmadin** [comment]
Roundings issue with ceiling function.  Fixed.
